#!/bin/bash

que_start() {
  ./src/disque-server --port 7711 &
  ./src/disque-server --port 7712 &
  ./src/disque-server --port 7713 &
  ./src/disque -p 7711 cluster meet 127.0.0.1 7712
  ./src/disque -p 7711 cluster meet 127.0.0.1 7713
}

cd ~
sudo apt-get install build-essential git -y

git clone https://github.com/antirez/disque.git

cd disque && make && que_start
