#!/bin/bash

install_colorsay() {
    curl -sSL https://raw.githubusercontent.com/goodjob1114/some-scripts/master/games/totoro/install-colorsay | bash
}

install_totoro_cows() {
    curl -sSL https://raw.githubusercontent.com/goodjob1114/some-scripts/master/games/totoro/cowsay-install-totoro | bash
}

install_totorosay() {
    totoro_bin=/usr/local/bin/totorosay
    update_bin=/usr/local/bin/update-totorosay
    _raw_github_path=https://raw.githubusercontent.com/goodjob1114/some-scripts/master/games/totoro
    [ ! -s ${totoro_bin} ] && sudo wget --output-document=${totoro_bin} ${_raw_github_path}/totorosay && sudo chmod +x ${totoro_bin}
    [ ! -s ${update_bin} ] && sudo wget --output-document=${update_bin} ${_raw_github_path}/update-totorosay && sudo chmod +x ${update_bin}
}

install_colorsay && install_totoro_cows && install_totorosay

exit 0
