#!/bin/bash

install_colorsay() {
    curl -sSL https://raw.githubusercontent.com/goodjob1114/some-scripts/master/games/totoro/install-colorsay | bash
}

install_totoro_cows() {
    curl -sSL https://raw.githubusercontent.com/goodjob1114/some-scripts/master/games/totoro/cowsay-install-totoro | bash
}

install_totorosay() {
    totoro_bin=/usr/local/bin/totorosay
    update_bin=/usr/local/bin/update-totorosay
    [ ! -s ${totoro_bin} ] && sudo wget --output-document=${totoro_bin} https://raw.githubusercontent.com/goodjob1114/some-scripts/master/games/totoro/totorosay && sudo chmod +x ${totoro_bin}
    [ ! -s ${update_bin} ] && sudo wget --output-document=${totoro_bin} https://raw.githubusercontent.com/goodjob1114/some-scripts/master/games/totoro/totorosay && sudo chmod +x ${update_bin}
}

install_colorsay && install_totoro_cows && install_totorosay
