#!/bin/bash

case ${OSTYPE} in
   linux-gnu) SHUF=shuf;;
   darwin*) SHUF=gshuf;;
   *) echo "Your device is not supported yet."; exit 1;;
esac

cows=( $(cowsay -l | grep -v "Cow files in") )
random_totoro=$(printf "%s\n" "${cows[@]}" | grep totoro | $SHUF -n 1)

if [ ! -t 0 ]; then
    cowsay -f ${random_totoro} | lolcat; exit 0;
fi

if [ $# -lt 1 ]; then
    fortune | cowsay -f ${random_totoro} | lolcat
else
    echo $1 | cowsay -f ${random_totoro} | lolcat
fi

exit 0
